### ISSUE TITLE
缺少配置文件

### ISSUE THREAD

**Issue by Cedric1314** [chaitin/xray-plugins#3]
[INF] 24-07-08 11:44:18 使用以下位置的配置文件：/root/.xray/xlint/xlint-config.yaml [app.go:422]
[INF] 24-07-08 11:44:18 未能正确加载配置文件或配置文件不存在，使用默认配置 [app.go:424]
[INF] 24-07-08 11:44:18 :gamma-lint: : Total File Count: 0 [lint.go:49]
[INF] 24-07-08 11:44:18 :gamma-lint: : Lint Done [lint.go:66]

**Comment by Jarcis-cy** [comment]
这个没问题，如果不需要配置，就正常使用就好了，需要配置再创建就行
